services:
  go_bd:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - crud_golang_rest

volumes:
  pgdata: {}

networks:
  crud_golang_rest:
    driver: bridge
    name: crud_golang_rest
